"""Update Subject model for separate theory and lab hours
Revision ID: 2cf9a09e8ac6
Revises: ee56382b63af
Create Date: 2025-07-02 08:19:27.277852
"""
from alembic import op
import sqlalchemy as sa

revision = '2cf9a09e8ac6'
down_revision = 'ee56382b63af'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theory_lectures_per_week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lab_sessions_per_week', sa.Integer(), nullable=True))
        batch_op.drop_column('lectures_per_week')
        batch_op.drop_column('is_lab')

    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_lab', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lectures_per_week', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('lab_sessions_per_week')
        batch_op.drop_column('theory_lectures_per_week')

    # ### end Alembic commands ###
