"""Add elective groups and link to subjects
Revision ID: 56c0af6a4ae2
Revises: a99b7a9b8b15
Create Date: 2025-09-19 16:13:24.897284
"""
from alembic import op
import sqlalchemy as sa

revision = '56c0af6a4ae2'
down_revision = 'a99b7a9b8b15'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elective_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elective_group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'elective_groups', ['elective_group_id'], ['id'])

    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('elective_group_id')

    op.drop_table('elective_groups')
    # ### end Alembic commands ###
