"""Add settings column to user
Revision ID: a99b7a9b8b15
Revises: 2cf9a09e8ac6
Create Date: 2025-07-05 16:52:56.503855
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = 'a99b7a9b8b15'
down_revision = '2cf9a09e8ac6'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False))

    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('settings')

    # ### end Alembic commands ###
