"""Add Division and Course models for OR-tools
Revision ID: ee56382b63af
Revises: dabeedf698eb
Create Date: 2025-07-01 08:14:24.348065
"""
from alembic import op
import sqlalchemy as sa

revision = 'ee56382b63af'
down_revision = 'dabeedf698eb'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lectures_per_week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_lab', sa.Boolean(), nullable=True))
        batch_op.drop_column('requires_lab')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('lecture_type')
        batch_op.drop_column('theory_hours_per_week')
        batch_op.drop_column('lab_hours_per_week')
        batch_op.drop_column('classes_taught')

    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classes_taught', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lab_hours_per_week', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('theory_hours_per_week', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lecture_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_lab', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_lab')
        batch_op.drop_column('lectures_per_week')

    op.drop_table('courses')
    op.drop_table('batches')
    op.drop_table('divisions')
    # ### end Alembic commands ###
